#!/usr/bin/python
# this is a smith configuration file

# set the default output folders
out="results"
DOCDIR="documentation"
OUTDIR="installers"
ZIPDIR="releases"
TESTDIR='test-suite'

APPNAME="NokyungAB"
VERSION="1.001"

font(target = 'NokyungAB.ttf',
	 source = 'font-source/Nokyung-R-no.sfd',
	 version = VERSION,
	 license = ofl('Nokyung'),
	 copyright = 'Copyright (c) 2008-2013 SIL International',
	 script='talu'
)
