#!/usr/bin/python
# this is a smith configuration file

# set the default output folders
out="results"
DOCDIR="documentation"
OUTDIR="installers"
ZIPDIR="releases"
TESTDIR='test-suite'

APPNAME="NokyungAA"
VERSION=1.001

font(target = 'NokyungAA.ttf',
	 source = 'font-source/Nokyung-R.sfd',
	 version = VERSION,
	 license = ofl('Nokyung'),
	 copyright = 'Copyright (c) 2008-2013 SIL International',
	 script='talu'
)
